
// Thêm 4 hàm này vào utils.js để kết nối Supabase
export const SUPA_URL = "https://hogksepvfxzhxyqllkxv.supabase.co/rest/v1/";
export const SUPA_KEY = "sb_publishable_hvyjuTVE11__0IHZGHi_DQ_GylrEYoT";

export const getSupaHeaders=()=>({'apikey':SUPA_KEY,'Authorization':`Bearer ${SUPA_KEY}`,'Content-Type':'application/json'});
export const fetchSupabaseDB=async()=>{try{const r=await fetch(`${SUPA_URL}/rest/v1/cms_store?id=eq.1&select=data`,{headers:getSupaHeaders()});if(r.ok){const res=await r.json();return res[0]?.data||null;}}catch(e){}return null;};
export const updateSupabaseDB=async(d)=>{try{await fetch(`${SUPA_URL}/rest/v1/cms_store?id=eq.1`,{method:'PATCH',headers:getSupaHeaders(),body:JSON.stringify({data:d})});}catch(e){}};
export const username='vietndj'; export const SECRET_PIN="0070";
export const safeEnc=fn=>{try{fn=decodeURIComponent(fn);}catch(e){}return encodeURIComponent(fn);};
export const encodeBase64UTF8Async=async(s)=>{const b=new TextEncoder().encode(s);let r='';for(let i=0;i<b.byteLength;i+=16384)r+=String.fromCharCode.apply(null,b.subarray(i,i+16384));return btoa(r);};
export const getHeaders=t=>t?{'Authorization':`Bearer ${t}`,'Accept':'application/vnd.github.v3+json'}:{'Accept':'application/vnd.github.v3+json'};
export const getContrastYIQ=h=>{if(!h)return '#1D1D1F';h=h.replace("#","");const y=((parseInt(h.substr(0,2),16)*299)+(parseInt(h.substr(2,2),16)*587)+(parseInt(h.substr(4,2),16)*114))/1000;return y>=128?'#1D1D1F':'#FFFFFF';};
export const fetchRawJSON=async(p,f,t)=>{try{const r=await fetch(`https://api.github.com/repos/${p}/contents/${safeEnc(f)}?t=${Date.now()}`,{headers:{...getHeaders(t),'Accept':'application/vnd.github.v3.raw'}});if(r.ok)return await r.json();}catch(e){}try{const r=await fetch(`https://${p.split('/')[0]}.github.io/${f}?t=${Date.now()}`);if(r.ok)return await r.json();}catch(e){}return null;};
export const fetchText=async(u,t)=>{try{const r=await fetch(u,{headers:{...getHeaders(t),'Accept':'application/vnd.github.v3.raw'}});return r.ok?await r.text():null;}catch(e){return null;}};
export const getFileShaSafe=async(p,f,t)=>{try{let d=await fetch(`https://api.github.com/repos/${p}/contents/${safeEnc(f)}?t=${Date.now()}`,{headers:getHeaders(t)}).then(r=>r.ok?r.json():null);if(d&&!Array.isArray(d))return d.sha;let d2=await fetch(`https://api.github.com/repos/${p}/contents/?t=${Date.now()}`,{headers:getHeaders(t)}).then(r=>r.ok?r.json():null);if(d2&&Array.isArray(d2)){const x=d2.find(x=>x.name===f);if(x)return x.sha;}return null;}catch(e){return null;}};
export const getLastContextFromDB=db=>{const f=db.files||[],t=db.tags||{},l=f.find(x=>x.repoName!==`${username}.github.io`&&x.repoName!==username);return l?{repo:`${username}/${l.repoName}`,tags:(t[`${l.repoName}/${l.fileName}`]||[]).join(', ')}:{repo:`${username}/${username}.github.io`,tags:''};};
export const removeAccents=s=>s?s.toString().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/gi,"d").toLowerCase():"";
export const getStringColor=s=>{if(!s)return '#86868B';const c=['#EF4444','#F97316','#F59E0B','#10B981','#06B6D4','#3B82F6','#8B5CF6','#D946EF','#F43F5E','#14B8A6'];let h=0;for(let i=0;i<s.length;i++)h=s.charCodeAt(i)+((h<<5)-h);return c[Math.abs(h)%c.length];};
export const getTimelineLabel=ts=>{if(!ts)return 'Khác';const n=new Date(),d=new Date(ts),st=new Date(n.getFullYear(),n.getMonth(),n.getDate()),td=new Date(d.getFullYear(),d.getMonth(),d.getDate()),df=Math.floor(Math.abs(st-td)/(1000*60*60*24));if(df===0)return '📍 Hôm nay';if(df<=7)return '🔥 Tuần này';if(df<=14)return '📅 Tuần trước';return `Tháng ${d.getMonth()+1}/${d.getFullYear()}`;};
export const generateSlug=(v,tg)=>{let s=v.toLowerCase().replace(/[áàảạãăắằẳẵặâấầẩẫậ]/gi,'a').replace(/[éèẻẽẹêếềểễệ]/gi,'e').replace(/[iíìỉĩị]/gi,'i').replace(/[óòỏõọôốồổỗộơớờởỡợ]/gi,'o').replace(/[úùủũụưứừửữự]/gi,'u').replace(/[ýỳỷỹỵ]/gi,'y').replace(/đ/gi,'d').replace(/\s+/g,'-').replace(/[^\w\-]+/g,'').replace(/\-\-+/g,'-').replace(/^-+|-+$/g,'');let a=tg.split(',').map(x=>x.trim()).filter(Boolean);if(a.length&&s){let ts=a.join('-').toLowerCase().replace(/\s+/g,'-');if(!s.includes(ts))s+='-'+ts;}if(s.length>140){s=s.substring(0,140);const l=s.lastIndexOf('-');if(l>100)s=s.substring(0,l);}return s;};

export const fetchAIBookDB=async()=>{try{const r=await fetch(`${SUPA_URL}/rest/v1/cms_store?id=eq.2&select=data`,{headers:getSupaHeaders()});if(r.ok){const res=await r.json();if(Array.isArray(res)&&res.length>0)return res[0].data||{};}}catch(e){}return{};};
export const updateAIBookDB=async(d)=>{try{const r=await fetch(`${SUPA_URL}/rest/v1/cms_store?id=eq.2`,{headers:getSupaHeaders()});const res=await r.json();const ex=Array.isArray(res)&&res.length>0;await fetch(ex?`${SUPA_URL}/rest/v1/cms_store?id=eq.2`:`${SUPA_URL}/rest/v1/cms_store`,{method:ex?'PATCH':'POST',headers:getSupaHeaders(),body:JSON.stringify(ex?{data:d}:{id:2,data:d})});}catch(e){}};

export const loadJSZip=async()=>{if(window.JSZip)return window.JSZip;return new Promise(r=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';s.onload=()=>r(window.JSZip);document.head.appendChild(s);});};